### ISSUE TITLE
templates in templates-directory cannot be used?

### ISSUE THREAD

**Issue by woutervh** [dpgaspar/fab_addon_audit#2]
How are you supposed to use the templates in the addon-templates-directory?
It seems this templates-directory is not getting registered.

**Comment by dpgaspar** [comment]
Feel free to reopen if this still relevant to you

**Comment by kisbam** [comment]
Can you please reopen the issue, I have several add-ons and can't use  the method self.render_template('test.html') in the view of add-on, for the moment I can only return html_content
